version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: movie-challenge
    volumes:
      - mongo-data:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - mongo-log:/data/log
    command: ['mongod', '--config', '/etc/mongod.conf']

volumes:
  mongo-data: { driver: local }
  mongo-log: { driver: local }
